Store/StoreApp/Controllers/CategoryController.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Repositories.Contracts;

namespace StoreApp.Controllers
{
	public class CategoryController : Controller
	{
		private IRepositoryManager _manager;
		public CategoryController (IRepositoryManager manager)
		{
			_manager = manager;
		}
		public IActionResult Index()
		{
			var model = _manager.Category.FindAll(false);
			return View(model);
		}
	}
}

Store/StoreApp/Controllers/OrderController.cs
using Entities.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace StoreApp.Controllers
{
	public class OrderController : Controller
	{
		private readonly IServiceManager _manager;
		private readonly Cart _cart;

		public OrderController(IServiceManager manager, Cart cart)
		{
			_manager = manager;
			_cart = cart;
		}

		[Authorize]
		public ViewResult Checkout() => View(new Order());

		[HttpPost]
		[ValidateAntiForgeryToken]

		public IActionResult Checkout([FromForm] Order order)
		{
			if (_cart.Lines.Count == 0)
			{
				ModelState.AddModelError("", "Sorry, your cart is empty '");
			}

			if (ModelState.IsValid)
			{
				order.Lines = _cart.Lines.ToArray();
				_manager.OrderService.SaveOrder(order);
				_cart.Clear();
				return RedirectToPage("/Complete" , new {OrderId = order.OrderId});
			}
			return View();
		}
	}
}

Store/StoreApp/Controllers/ProductController.cs
using Entities.Models;
using Entities.RequestParameters;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Repositories;
using Repositories.Contracts;
using Services.Contracts;
using StoreApp.Models;

namespace StoreApp.Controllers
{
    public class ProductController : Controller 
    {

        private readonly IServiceManager _manager;

		public ProductController(IServiceManager manager)
		{
			_manager = manager;
		}

		public IActionResult Index(ProductRequestParameters p)
        {
            var products = _manager.ProductService.GetAllProductsWithDetails(p);
            var pagination = new Pagination()
            {
                CurrentPage = p.PageNumber,
                ItemsPerPage = p.PageSize,
                TotalItems = _manager.ProductService.GetAllProducts(false).Count()
            };
            return View(new ProductListViewModel()
            {
                Products = products,
                Pagination = pagination
            });
        }
        public IActionResult Get([FromRoute(Name ="id")]int id)
        {
            var model = _manager.ProductService.GetOneProduct(id,false);
            ViewData["Title"] = model?.ProductName;
            return View(model);
        }
    }
}

Store/StoreApp/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>StoreApp - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/StoreApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" asp-append-version="true" />
</head>
<body>
    <header>
        <partial name="_Navbar" />
        @RenderSection("Header" , false)
       
    </header>
    <div class="container">

        <div>
            <partial name="_Notification" />
        </div>

        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        @RenderSection("Footer", false)
  
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @* <script src="~/lib/jquery/jquery.min.js"></script> *@
     <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script> 
    @* <script src="~/js/site.js"></script> *@
    <script src="~/lib/font-awesome/js/all.js"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

@section Scripts
{
    <script type="text/javascript">
        $(document).ready(() => {
            $('[data-toggle = "tooltip"]').tooltip()
        })
        
    </script>
}

Store/StoreApp/Areas/Admin/Views/Shared/_Navbar.cshtml
<nav class="navbar bg-dark navbar-expand-lg bg-body-tertiary">
	<div class="container">
		<a class="navbar-brand text-white" href="/">ADMIN</a>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse d-sm-inline-flex justify-content-between" id="navbarNav">

			<ul class="navbar-nav">
				<li class="nav-item">
					<a class="nav-link" text-white aria-current="page" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" text-white aria-current="page" asp-controller="Product" asp-action="Index">Products(@await Component.InvokeAsync("ProductSummary"))</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" text-white aria-current="page" asp-controller="Category" asp-action="Index">Categories</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" text-white aria-current="page" asp-controller="Order" asp-action="Index">Orders</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" text-white aria-current="page" asp-controller="Role" asp-action="Index">Roles</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" text-white aria-current="page" asp-controller="User" asp-action="Index">Users</a>
				</li>
			</ul>
			<ul class="navbar-nav" text-white">
				<li class="nav-item">
					<a target="_blank" class="nav-link" text-white aria-current="page" asp-area="" asp-controller="Home" asp-action="Index">Web</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" text-white aria-current="page" asp-area="" asp-controller="Account" asp-action="Logout">
						<i class="fa-solid fa-right-from-bracket"></i>
						Logout</a>
				</li>
			</ul>
		</div>
	</div>
</nav>  
@* admin *@